version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis-server
  redis-server:
    image: 'redis'
    volumes:
      - redis-data:/data
volumes:
  redis-data: